binaries:
  - ruby-1.9.3-p448
  - ruby-2.0.0-p247
distributions:
  centos_59_64bit: http://tag1consulting.com/files/centos-5.9-x86-64-minimal.box
  centos_64_64bit: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130309.box
  debian_603_64bit_squeeze: http://dl.dropbox.com/u/937870/VMs/squeeze64.box
  debian_60_32bit_squeeze: https://dl.dropbox.com/u/2289657/squeeze32-vanilla.box
  debian_70_32bit_wheezy: https://rvm.io/vboxes/debian-7.0-i386-netboot.box
  debian_70_64bit_wheezy: https://rvm.io/vboxes/debian-7.0-amd64-netboot.box
  fedora_18_64bit: http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210.box
  fedora_19_64bit: https://rvm.io/vboxes/fedora-19-x86_64.box
  opensuse_123_64bit: https://rvm.io/vboxes/opensuse-12.3-NET-x86_64.box
  ubuntu_1004_32bit_lucid: http://files.vagrantup.com/lucid32.box
  ubuntu_1004_64bit_lucid: http://files.vagrantup.com/lucid64.box
  ubuntu_1204_32bit_precise: http://files.vagrantup.com/precise32.box
  ubuntu_1204_64bit_precise: http://files.vagrantup.com/precise64.box
  ubuntu_1210_64bit_quantal: https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box
  ubuntu_1304_32bit_raring: http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-i386-vagrant-disk1.box
  ubuntu_1304_64bit_raring: http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box
distros:
    centos_59: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-59-x64-vbox4210-nocm.box'
    centos_64: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
    debian_60: 'http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210-nocm.box'
    fedora_18: 'http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210-nocm.box'
    ubuntu_1204: 'http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
    ubuntu_1210: 'http://cloud-images.ubuntu.com/vagrant/quantal/current/quantal-server-cloudimg-amd64-vagrant-disk1.box'
    ubuntu_1304: 'http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box'
    ubuntu_1310: 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'
