---
binaries:
  - ruby-1.9.3-p429
  - ruby-2.0.0-p195
distributions:
  centos_59_64bit: http://tag1consulting.com/files/centos-5.9-x86-64-minimal.box
  centos_64_64bit: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130309.box
  debian_603_64bit_squeeze: http://dl.dropbox.com/u/937870/VMs/squeeze64.box
  debian_60_32bit_squeeze: https://dl.dropbox.com/u/2289657/squeeze32-vanilla.box
  fedora_18_64bit: http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210.box
  ubuntu_1004_32bit_lucid: http://files.vagrantup.com/lucid32.box
  ubuntu_1004_64bit_lucid: http://files.vagrantup.com/lucid64.box
  ubuntu_1204_32bit_precise: http://files.vagrantup.com/precise32.box
  ubuntu_1204_64bit_precise: http://files.vagrantup.com/precise64.box
  ubuntu_1210_64bit_quantal: https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box
  ubuntu_1304_64bit_raring: http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box
